export const MY_STACK = [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Next",
    "Redux",
    "Apollo Client",
    "Styled Components",
    "Formik",
    "Yup",
    "Swiper",
    "Node JS",
    "Fastify",
];
